### PR TITLE
Fix broken tests + Add code coverage tracking

### LINKED ISSUE #18: GraphClientFactory for PHP
The GraphClientFactory will give SDK users the option to create and define their own HTTP client configuration and pass it to Graph() to be used for requests.

Consider support for arbitrary HttpClients so that customer can bring their own clients to use in our GraphClient.

Reference:
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/GraphClientFactory.md 

Related to:
microsoftgraph/msgraph-sdk-php#328 , microsoftgraph/msgraph-sdk-php#339 , microsoftgraph/msgraph-sdk-php#283 , microsoftgraph/msgraph-sdk-php#232 

Task breakdown:
- [x] Design doc written and reviewed
- [x] Implement HttpClientFactory
- [x] Make changes to GraphRequest classes to remove HTTP client concerns
- [x] Update tests
- [x] Document breaking changes in an upgrade guide

[AB#8906](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8906)

### PR DESCRIPTION
**Pull request by Ndiritu**
This PR:
- fixes failing tests as a result of refactoring done in #4 
- fixes bugs in #4 that have been identified during testing
- increases test coverage of our GraphRequest classes

closes #18

### CODE REVIEW

File: src/Http/GraphRequest.php [hunk 1]
```diff
@@ -162,14 +152,18 @@ public function setReturnType(string $returnClass): self
...
+     * Adds custom headers to the request
+     *
+     * @param array<string, string|string[]> $headers An array of custom headers
+     *
+     * @return GraphRequest object
+     * @throws GraphClientException if attempting to overwrite SdkVersion header
+     */
     public function addHeaders(array $headers): self
     {
+        if (array_key_exists("SdkVersion", $headers)) {
```
Comment (MIchaelMainer) [inline src/Http/GraphRequest.php:164]: I appreciate this. We should do this in other SDKs.

File: src/Http/GraphRequestUtil.php [hunk 2]
```diff
@@ -30,16 +30,27 @@ class GraphRequestUtil
...
+     * @return UriInterface
+     * @throws \InvalidArgumentException
      */
-    public static function getRequestUri(string $baseUrl, string $endpoint, string $apiVersion = "v1.0"): ?UriInterface {
-        // If endpoint is a full url, ensure the host is a national cloud or custom host
+    public static function getRequestUri(string $baseUrl, string $endpoint, string $apiVersion = "v1.0"): UriInterface {
+        // If endpoint is a full url, ensure the host is a national cloud
         if (parse_url($endpoint, PHP_URL_SCHEME)) {
-            return (NationalCloud::containsNationalCloudHost($endpoint)) ? new Uri($endpoint) : null;
+            if (NationalCloud::containsNationalCloudHost($endpoint)) {
```
Comment (MIchaelMainer) [inline src/Http/GraphRequestUtil.php:39]: My only concern here is that as new national (or even state-level) clouds come on board, we will have to keep updating NationalCloud.php. Now mind you, this hasn't happened often, yet, so perhaps this is good value for the customer.

As it is now, if they get the cloud wrong, they will get an error along the lines that the host name doesn't resolve. That will be a decent hint for them to check the cloud.

File: src/Http/GraphRequestUtil.php [hunk 3]
```diff
@@ -30,16 +30,27 @@ class GraphRequestUtil
...
+                return new Uri($endpoint);
+            }
+            throw new \InvalidArgumentException("Invalid national cloud host in endpoint=".$endpoint.". See https://docs.microsoft.com/en-us/graph/deployments#microsoft-graph-and-graph-explorer-service-root-endpoints.");
         }
-        $relativeUrl = (NationalCloud::containsNationalCloudHost($baseUrl)) ? "/".$apiVersion : "";
-        $relativeUrl .= (substr($endpoint, 0, 1) == "/") ? $endpoint : "/".$endpoint;
-        return UriResolver::resolve(new Uri($baseUrl), new Uri($relativeUrl));
+        if ($baseUrl) {
+            $urlParts = parse_url($baseUrl);
+            if (!$urlParts || !array_key_exists("scheme", $urlParts) || !array_key_exists("host", $urlParts)) {
```
Comment (MIchaelMainer) [inline src/Http/GraphRequestUtil.php:46]: There is a similar check in `NationalCloud::containsNationalCloudHost($baseUrl))` so we could use it to validate here, I think.

**Review by MIchaelMainer — COMMENTED** [review]
Do you have code coverage % info for before and after?  This QA improvement would be useful for inclusion in quality review, as well as to put in your own review.

File: composer.json [hunk 4]
```diff
@@ -22,8 +22,7 @@
 	"require-dev": {
 		"phpunit/phpunit": "^8.0 || ^9.0",
 		"mikey179/vfsstream": "^1.2",
-		"vimeo/psalm": "^4.8",
-		"microsoft/microsoft-graph": "^1.34"
+		"vimeo/psalm": "^4.8"
```
[the remark this answers is not in the document]
Comment (Ndiritu) [reply composer.json:25]: Yes nice catch

File: src/Http/GraphRequestUtil.php (hunk 3 above)
Comment (Ndiritu) [reply src/Http/GraphRequestUtil.php:46]: I had added this validation separately to cover the case where customers pass custom base URL's when setting up the request.
I can make the National cloud host validation & custom base Url validation cleaner though since there are similar checks across both.

File: src/Http/GraphRequestUtil.php (hunk 2 above)
Comment (Ndiritu) [reply src/Http/GraphRequestUtil.php:39]: Interesting pointer. I agree that this adds a burden on us to always be up to date & we'd potentially break a customer's experience.

I am happy with removing this restriction and allowing any valid full endpoint to work.

Worst case (without this validation) is the host name resolution error which would still prompt a user to double check their hostname

Comment (Ndiritu) [reply src/Http/GraphRequestUtil.php:39]: Which leads me to need to update [this](https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/5/files/9fbe9e9a2290e550cd267cad63741de4e65a2cde#diff-849151e7b2ea35fbfeca79419f39a80ebc43ed0c66cd50f309db361f7682c4a9R347) to check the full request URI to prevent sending tokens to non-graph endpoints

File: composer.json (hunk 4 above)
[the remark this answers is not in the document]
Comment (Ndiritu) [reply composer.json]: Done

File: src/Http/GraphRequestUtil.php (hunk 2 above)
Comment (Ndiritu) [reply src/Http/GraphRequestUtil.php]: Removed extra validation + updated add headers logic

File: src/Http/GraphRequestUtil.php (hunk 3 above)
Comment (Ndiritu) [reply src/Http/GraphRequestUtil.php]: - Refactored this to prevent parsing the url twice.
- It wouldn't be possible to only use `NationalCloud::containsNationalCloudHost()` to validate a base url since we need to support non-graph base urls (https://github.com/microsoftgraph/msgraph-sdk-design/pull/45)

**Comment by Ndiritu** [comment]
> Do you have code coverage % info for before and after? This QA improvement would be useful for inclusion in quality review, as well as to put in your own review.

- I've setup code coverage config using PHPUnit to this PR.
- When validating a PR, we will be able to see the coverage summary in the github actions output for now. 
- Better solutions would be able to make this an action on it's own and potentially block PRs if they reduce the test coverage. PHPUnit doesn't seem to support a simple GitHub Action to do this = more work. Created a [tracking item](https://github.com/microsoftgraph/msgraph-sdk-php/issues/585)
- PHPUnit produces a bunch of [metrics](https://phpunit.readthedocs.io/en/9.5/code-coverage-analysis.html#software-metrics-for-code-coverage). Path coverage seems to be most useful one IMO

Before - (current `main`)
```
Code Coverage Report:
  2021-08-16 10:16:20

 Summary:
  Classes: 14.29% (1/7)
  Methods: 62.26% (33/53)
  Paths:   60.78% (62/102)
  Branches:   84.50% (109/129)
  Lines:   79.25% (210/265)
```
After - (this PR)
```
Code Coverage Report:
  2021-08-16 10:15:12

 Summary:
  Classes: 66.67% (6/9)
  Methods: 83.87% (52/62)
  Paths:   62.42% (93/149)
  Branches:   96.09% (172/179)
  Lines:   90.67% (243/268)
```

To see more detail, running coverage locally would produce a `coverage/` folder (gitignored) containing HTML pages with deeper analysis of which code paths still need testing:
```php -xdebug.mode=coverage ./vendor/bin/phpunit```

Biggest gaps are in `GraphCollectionRequest` and `Enum` classes

File: src/Http/GraphRequest.php [hunk 5]
```diff
@@ -139,21 +124,27 @@ public function getReturnsStream()
...
+     * @throws GraphClientException when $returnClass is not an existing class
+     */
     public function setReturnType(string $returnClass): self
     {
+        if (!class_exists($returnClass) && !interface_exists($returnClass)) {
+            throw new GraphClientException("Return type specified does not match an existing class definition");
+        }
         $this->returnType = $returnClass;
-        if ($this->returnType == "GuzzleHttp\Psr7\Stream") {
+        if ($this->returnType == StreamInterface::class) {
```
Comment (SilasKenneth) [inline src/Http/GraphRequest.php:147]:
```suggestion
        if ($this->returnType === StreamInterface::class) {
```

File: src/Http/HttpClientFactory.php [hunk 6]
```diff
@@ -87,7 +93,7 @@ public static function nationalCloud(string $nationalCloud = NationalCloud::GLOB
      */
     public static function clientConfig(array $config): HttpClientFactory {
```
Comment (SilasKenneth) [inline src/Http/HttpClientFactory.php:94]:
```suggestion
    public static function setClientConfig(array $config): HttpClientFactory {
```

File: tests/Http/Request/GraphRequestUtilTest.php [hunk 7]
```diff
@@ -79,17 +76,10 @@ function testGetRequestUriWithoutNationalCloudHostDoesntSetApiVersion() {
 
     function testGetRequestUriWithInvalidFullEndpointUrlThrowsException() {
         $this->expectException(\InvalidArgumentException::class);
-        $endpoint = "http:/microsoft.com:localhost\$endpoint";
+        $endpoint = "http/microsoft.com:localhost\$endpoint";
```
Comment (SilasKenneth) [inline tests/Http/Request/GraphRequestUtilTest.php:79]:
```suggestion
        $endpoint = 'http/microsoft.com:localhost\$endpoint';
```

File: tests/Http/Request/GraphRequestUtilTest.php [hunk 8]
```diff
@@ -79,17 +76,10 @@ function testGetRequestUriWithoutNationalCloudHostDoesntSetApiVersion() {
...
 
-    function testGetRequestUrlWithInvalidBaseUrlAndEndpointThrowsException() {
-        $this->expectException(\InvalidArgumentException::class);
-        $baseUrl = "https://graph.microsoft.com";
-        $endpoint = "http:/microsoft.com:localhost\$endpoint";
-        $uri = GraphRequestUtil::getRequestUri($baseUrl, $endpoint, $this->apiVersion);
-    }
-
     function testGetQueryParamConcatenatorWithExistingQueryParams() {
         $uri = new Uri("https://graph.microsoft.com?\$skip=10");
```
Comment (SilasKenneth) [inline tests/Http/Request/GraphRequestUtilTest.php:84]:
```suggestion
        $uri = new Uri('https://graph.microsoft.com?$skip=10');
```

**Review by MIchaelMainer — APPROVED** [review]

File: tests/Http/SampleGraphResponsePayload.php [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+{
+    const ENTITY_PAYLOAD = [
+        "@odata.id" => "https://graph.microsoft.com/v2/dcd219dd-bc68-4b9b-bf0b-4a33a796be35",
+        "jobTitle" => "developer",
+        "givenName" => "user1"
+    ];
+
+    const COLLECTION_PAYLOAD = [
+        "@odata.count" => 2,
+        "@odata.nextLink" => "https://graph.microsoft.com/me/users?\$skip=2&\$top=2",
```
Comment (SilasKenneth) [inline tests/Http/SampleGraphResponsePayload.php:25]:
```suggestion
        "@odata.nextLink" => 'https://graph.microsoft.com/me/users?$skip=2&$top=2',
```

**Review by SilasKenneth — CHANGES_REQUESTED** [review]

File: .github/workflows/pr-validation.yml [hunk 10]
```diff
@@ -20,6 +20,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2.3.4
+    - name: Setup PHP and Xdebug for Code Coverage report
+      uses: shivammathur/setup-php@v2
+      with:
+        php-version: '7.x'
```
Comment (SilasKenneth) [inline .github/workflows/pr-validation.yml:26]:
```suggestion
        php-version: '7.3'
```

Can we possibly put 7.3 since that's the minimum PHP version we use.

File: src/Http/GraphRequest.php [hunk 11]
```diff
@@ -162,14 +153,18 @@ public function setReturnType(string $returnClass): self
...
+     *
+     * @return GraphRequest object
+     * @throws GraphClientException if attempting to overwrite SdkVersion header
+     */
     public function addHeaders(array $headers): self
     {
+        if (array_key_exists("SdkVersion", $headers)) {
+            throw new GraphClientException("Cannot overwrite SdkVersion header");
+        }
         $this->headers = array_merge_recursive($this->headers, $headers);
```
Comment (SilasKenneth) [inline src/Http/GraphRequest.php:168]: Any reasons for a recursive merge?

File: src/Http/GraphResponse.php [hunk 12]
```diff
@@ -111,15 +114,15 @@ public function getBody()
     */
     public function getRawBody()
     {
-        return $this->_body;
+        return (is_null($this->_body)) ? null : $this->_body->getContents();
```
Comment (SilasKenneth) [inline src/Http/GraphResponse.php:117]:
```suggestion
        return ($this->_body) ?: $this->_body->getContents();
```

**Review by SilasKenneth — CHANGES_REQUESTED** [review]

File: src/Http/GraphRequest.php (hunk 11 above)
Comment (Ndiritu) [reply src/Http/GraphRequest.php:168]: It allows us to append multiple values to a given header for headers that support multiple values e.g. Accept, Accept-Language, Cache-Control etc

Comment (Ndiritu) [reply src/Http/GraphRequest.php:168]: Adding a comment for future clarity

Comment (Ndiritu) [reply src/Http/GraphRequest.php:168]: There's a [test](https://github.com/microsoftgraph/msgraph-sdk-php-core/blob/philip/fix/tests/tests/Http/Request/GraphRequestTest.php#L190) to cover this as well

File: src/Http/HttpClientFactory.php (hunk 6 above)
Comment (Ndiritu) [reply src/Http/HttpClientFactory.php:94]: Updated naming of all setters methods in this class

File: src/Http/GraphRequest.php (hunk 5 above)
Comment (Ndiritu) [reply src/Http/GraphRequest.php:147]: Updated. Although we're guaranteed of a string $returnClass due to the strong argument type

File: tests/Http/Request/GraphRequestUtilTest.php (hunk 7 above)
Comment (Ndiritu) [reply tests/Http/Request/GraphRequestUtilTest.php:79]: Updated

File: tests/Http/Request/GraphRequestUtilTest.php (hunk 8 above)
Comment (Ndiritu) [reply tests/Http/Request/GraphRequestUtilTest.php:84]: Updated

File: tests/Http/SampleGraphResponsePayload.php (hunk 9 above)
Comment (Ndiritu) [reply tests/Http/SampleGraphResponsePayload.php:25]: Updated

File: src/Http/GraphResponse.php (hunk 12 above)
Comment (Ndiritu) [reply src/Http/GraphResponse.php:117]: Updated

File: src/Http/GraphRequestUtil.php [hunk 13]
```diff
@@ -30,16 +30,36 @@ class GraphRequestUtil
...
-        $relativeUrl = (NationalCloud::containsNationalCloudHost($baseUrl)) ? "/".$apiVersion : "";
-        $relativeUrl .= (substr($endpoint, 0, 1) == "/") ? $endpoint : "/".$endpoint;
-        return UriResolver::resolve(new Uri($baseUrl), new Uri($relativeUrl));
+        if ($baseUrl) {
+            $baseUrlParts = parse_url($baseUrl);
+            if (!self::isValidBaseUrl($baseUrlParts)) {
+                throw new \InvalidArgumentException("Invalid baseUrl=".$baseUrl.". Ensure URL has scheme and host");
+            }
+            $relativeUrl = (NationalCloud::containsNationalCloudHostFromUrlParts($baseUrlParts)) ? "/".$apiVersion : "";
+            $relativeUrl .= (substr($endpoint, 0, 1) == "/") ? $endpoint : "/".$endpoint;
```
[the remark this answers is not in the document]
Comment (Ndiritu) [reply src/Http/GraphRequestUtil.php:47]: Updated

File: .github/workflows/pr-validation.yml (hunk 10 above)
Comment (Ndiritu) [reply .github/workflows/pr-validation.yml:26]: Updated.

**Review by SilasKenneth — APPROVED** [review]
